version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - db
      - redis
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 2008Laila
      MYSQL_DATABASE: appdb
    ports:
      - '3306:3306'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
